"""Render captions + overlays into an Advanced SubStation Alpha (.ass) file.

Why ASS? libass (bundled with ffmpeg) renders text with outlines, shadows,
per-word colours, animated scale (karaoke pop) and vector shapes in a single
GPU-free pass. That lets us draw **subtitles, the progress bar, the brand
watermark and the intro/outro cards** with one ``ass=`` filter instead of a
fragile stack of ``drawtext``/``drawbox`` filters (which are not even compiled
into every ffmpeg build).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from contentforge.config.schema import BrandingConfig, ProgressBarConfig, SubtitleConfig
from contentforge.log import get_logger
from contentforge.subtitles.captions import Caption
from contentforge.utils import atomic_write_text, format_ass_time, hex_to_ass_color

log = get_logger("ass")


@dataclass
class OverlaySpec:
    """Extra non-subtitle overlays to render."""

    duration: float
    progress_bar: ProgressBarConfig | None = None
    branding: BrandingConfig | None = None
    intro_text: str = ""
    outro_text: str = ""
    intro_seconds: float = 2.2
    outro_seconds: float = 2.5


class AssRenderer:
    def __init__(self, config: SubtitleConfig, width: int = 1080, height: int = 1920):
        self.config = config
        self.width = width
        self.height = height

    # ------------------------------------------------------------- styles
    def _styles(self, branding: BrandingConfig | None) -> str:
        c = self.config
        primary = hex_to_ass_color(c.primary_color)
        outline = hex_to_ass_color(c.outline_color)
        shadow_col = hex_to_ass_color("#000000", alpha=0x60)
        highlight = hex_to_ass_color(c.highlight_color)
        # Alignment 2 = bottom-centre; vertical placement handled via MarginV
        margin_v = int(self.height * (1 - c.position_v))
        font_size = c.font_size
        style = c.style
        outline_w = c.outline_width
        shadow = c.shadow
        if style == "clean":
            outline_w, shadow = 3, 0
        elif style == "minimal":
            outline_w, shadow = 2, 0
            font_size = int(font_size * 0.85)
        bold = -1 if style in ("bold-pop", "karaoke") else 0
        lines = [
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
            "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
            "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
            f"Style: Caption,{c.font},{font_size},{primary},{highlight},{outline},{shadow_col},{bold},0,0,0,"
            f"100,100,1,0,1,{outline_w},{shadow},2,60,60,{margin_v},1",
            f"Style: Highlight,{c.font},{font_size},{highlight},{highlight},{outline},{shadow_col},-1,0,0,0,"
            f"100,100,1,0,1,{outline_w},{shadow},2,60,60,{margin_v},1",
        ]
        brand_primary = hex_to_ass_color(branding.primary_color) if branding else primary
        brand_secondary = hex_to_ass_color(branding.secondary_color) if branding else primary
        wm_alpha = int(255 * (1 - (branding.watermark_opacity if branding else 0.85)))
        wm_col = hex_to_ass_color(
            branding.secondary_color if branding else "#FFFFFF", alpha=wm_alpha
        )
        wm_size = branding.font_size if branding else 38
        lines += [
            f"Style: Watermark,{c.font},{wm_size},{wm_col},{wm_col},{outline},&H80000000,-1,0,0,0,100,100,0,0,1,2,1,9,40,40,40,1",
            f"Style: Shape,{c.font},20,{brand_primary},{brand_primary},&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,7,0,0,0,1",
            f"Style: Card,{c.font},{int(font_size * 1.1)},{brand_secondary},{brand_secondary},{outline},&H80000000,-1,0,0,0,100,100,0,0,1,4,2,5,80,80,0,1",
            f"Style: CardAccent,{c.font},{int(font_size * 0.6)},{brand_primary},{brand_primary},{outline},&H80000000,-1,0,0,0,100,100,2,0,1,3,1,5,80,80,0,1",
        ]
        return "\n".join(lines)

    def _header(self) -> str:
        return "\n".join(
            [
                "[Script Info]",
                "; Generated by ContentForge-AI",
                "ScriptType: v4.00+",
                f"PlayResX: {self.width}",
                f"PlayResY: {self.height}",
                "WrapStyle: 0",
                "ScaledBorderAndShadow: yes",
                "YCbCr Matrix: TV.709",
                "",
            ]
        )

    # ------------------------------------------------------------- events
    def caption_events(self, captions: list[Caption]) -> list[str]:
        c = self.config
        events: list[str] = []
        hl = hex_to_ass_color(c.highlight_color).replace("&H00", "&H")  # \c takes &HBBGGRR&
        primary = hex_to_ass_color(c.primary_color).replace("&H00", "&H")
        for cap in captions:
            start, end = format_ass_time(cap.start), format_ass_time(cap.end)
            if c.style == "karaoke":
                # \k durations in centiseconds; SecondaryColour -> PrimaryColour sweep per word
                parts = []
                for w in cap.words:
                    cs = max(1, int(round((w.end - w.start) * 100)))
                    parts.append(f"{{\\kf{cs}}}{_esc(w.text)}")
                text = "{\\fad(60,60)}" + " ".join(parts)
                events.append(f"Dialogue: 2,{start},{end},Caption,,0,0,0,,{text}")
                continue
            words_markup = []
            for w in cap.words:
                if w.highlight:
                    words_markup.append(f"{{\\c{hl}&}}{_esc(w.text)}{{\\c{primary}&}}")
                else:
                    words_markup.append(_esc(w.text))
            body = " ".join(words_markup)
            if c.style == "bold-pop":
                # scale pop-in: 80% -> 100% over 120 ms
                body = "{\\fad(40,40)\\fscx82\\fscy82\\t(0,120,\\fscx100\\fscy100)}" + body
            elif c.style == "clean":
                body = "{\\fad(60,60)}" + body
            events.append(f"Dialogue: 2,{start},{end},Caption,,0,0,0,,{body}")
        return events

    def overlay_events(self, spec: OverlaySpec) -> list[str]:
        events: list[str] = []
        W, H, D = self.width, self.height, spec.duration
        end = format_ass_time(D)

        # ---- progress bar (vector shape whose horizontal scale animates 0->100 %)
        if spec.progress_bar and spec.progress_bar.enabled:
            pb = spec.progress_bar
            y0 = 0 if pb.position == "top" else H - pb.height
            bg = hex_to_ass_color(pb.background)
            fg = hex_to_ass_color(pb.color)
            rect = f"m 0 0 l {W} 0 l {W} {pb.height} l 0 {pb.height}"
            events.append(
                f"Dialogue: 0,0:00:00.00,{end},Shape,,0,0,0,,"
                f"{{\\an7\\pos(0,{y0})\\c{bg[:2] + bg[4:]}&\\1a{bg[2:4]}&\\p1}}{rect}{{\\p0}}"
            )
            events.append(
                f"Dialogue: 1,0:00:00.00,{end},Shape,,0,0,0,,"
                f"{{\\an7\\pos(0,{y0})\\c{fg[:2] + fg[4:]}&\\fscx0\\t(0,{int(D * 1000)},\\fscx100)\\p1}}{rect}{{\\p0}}"
            )

        # ---- watermark
        if spec.branding and spec.branding.enabled and spec.branding.watermark_text:
            b = spec.branding
            an = {"top-left": 7, "top-right": 9, "bottom-left": 1, "bottom-right": 3}[
                b.watermark_position
            ]
            bar_h = (
                spec.progress_bar.height
                if spec.progress_bar and spec.progress_bar.position == "top"
                else 0
            )
            x = 40 if an in (7, 1) else W - 40
            # keep the watermark in the strip above the intro card (card starts at 6 % of H)
            y = bar_h + 18 if an in (7, 9) else H - 60
            events.append(
                f"Dialogue: 3,0:00:00.00,{end},Watermark,,0,0,0,,{{\\an{an}\\pos({x},{y})}}{_esc(b.watermark_text)}"
            )

        # ---- intro title card (hook text) & outro CTA card
        if spec.branding and spec.branding.enabled:
            b = spec.branding
            bg = hex_to_ass_color(b.background_color, alpha=0x55)
            if b.intro_title and spec.intro_text and D > spec.intro_seconds + 1:
                s, e = 0.0, spec.intro_seconds
                events.append(_card_bg(W, H, s, e, bg, top=int(H * 0.07), height=int(H * 0.21)))
                events.append(
                    f"Dialogue: 5,{format_ass_time(s)},{format_ass_time(e)},Card,,0,0,0,,"
                    f"{{\\an5\\pos({W // 2},{int(H * 0.175)})\\fad(150,250)\\q2}}{_esc(_wrap(spec.intro_text, 26))}"
                )
            if b.outro_cta and spec.outro_text and D > spec.outro_seconds + 1:
                s, e = D - spec.outro_seconds, D
                events.append(_card_bg(W, H, s, e, bg, top=int(H * 0.30), height=int(H * 0.26)))
                events.append(
                    f"Dialogue: 5,{format_ass_time(s)},{format_ass_time(e)},Card,,0,0,0,,"
                    f"{{\\an5\\pos({W // 2},{int(H * 0.40)})\\fad(250,0)\\q2}}{_esc(_wrap(spec.outro_text, 24))}"
                )
                events.append(
                    f"Dialogue: 5,{format_ass_time(s)},{format_ass_time(e)},CardAccent,,0,0,0,,"
                    f"{{\\an5\\pos({W // 2},{int(H * 0.50)})\\fad(250,0)}}{_esc(b.watermark_text.upper())}"
                )
        return events

    # -------------------------------------------------------------- write
    def render(
        self, captions: list[Caption], out_path: Path, overlays: OverlaySpec | None = None
    ) -> Path:
        branding = overlays.branding if overlays else None
        parts = [
            self._header(),
            self._styles(branding),
            "",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        ]
        if overlays:
            parts += self.overlay_events(overlays)
        if self.config.enabled:
            parts += self.caption_events(captions)
        atomic_write_text(out_path, "\n".join(parts) + "\n")
        log.debug("Wrote ASS overlay with %d captions -> %s", len(captions), out_path)
        return out_path


def _card_bg(W: int, H: int, s: float, e: float, colour: str, *, top: int, height: int) -> str:
    rect = f"m 60 {top} l {W - 60} {top} l {W - 60} {top + height} l 60 {top + height}"
    return (
        f"Dialogue: 4,{format_ass_time(s)},{format_ass_time(e)},Shape,,0,0,0,,"
        f"{{\\an7\\pos(0,0)\\c{colour[:2] + colour[4:]}&\\1a{colour[2:4]}&\\fad(150,200)\\p1}}{rect}{{\\p0}}"
    )


def _wrap(text: str, width: int) -> str:
    words, lines, cur = text.split(), [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return "\\N".join(lines[:4])


def _esc(text: str) -> str:
    """Escape ASS special characters (keep our own ``\\N`` line breaks)."""
    return text.replace("{", "(").replace("}", ")")
